### ISSUE TITLE
IO device support checklist: EMMC

### ISSUE THREAD

**Issue by archshift** [archshift/llama#1]
- [x] Add device boilerplate code 
- [ ] Verify register read-/writability
- [x] Rudimentary read from SD card file
- [x] Rudimentary write to SD card file
- [ ] SD card file autogen
- [x] Read from NAND file
- [x] Write to NAND file
- [ ] NAND file autogen
- [ ] CSD register
- [x] CID register
- [x] DATA32 reads
- [x] DATA32 writes
- [x] Interrupts
- [ ] Cached read/write for better performance
