### ISSUE TITLE
Screen output support checklist

### ISSUE THREAD

**Issue by archshift** [archshift/llama#2]
- [x] GUI first steps
- [x] Implement framebuffer memory blitting mechanism
- [x] Functioning ARM9-side screen output
- [ ] Screen out method configurability (GW-style, Brahma/Arm9loaderhax-style)
