### ISSUE TITLE
IO device support checklist: AES

### ISSUE THREAD

**Issue by archshift** [archshift/llama#4]
- [x] AES-CBC encryption/decryption
- [ ] AES-CCM encryption/decryption
- [x] AES-CTR encryption/decryption
- [x] AES-ECB encryption/decryption
- [x] 3DS KeyX/Y keygen
- [ ] TWL key support
- [ ] Interrupts
- [ ] DMA
