### ISSUE TITLE
Message-based notification system checklist

### ISSUE THREAD

**Issue by archshift** [archshift/llama#5]
- [x] Initial implementation
- [ ] IO device communication via dedicated IO thread
- [ ] More heavily-enforced (at type level) subscription/permission model
- [x] Centralize client permissions
- [ ] Endpoint-to-endpoint (no intermediate thread) transfer
