### ISSUE TITLE
IO device support checklist: XDMA, NDMA

### ISSUE THREAD

**Issue by archshift** [archshift/llama#8]
- [x] XDMA infrastructure stub
- [x] Barebones Corelink DMA instruction interpreting
- [x] XDMA loads/stores
- [ ] XDMA peripheral support
- [x] XDMA peripheral waiting
- [ ] Corelink events
- [x] NDMA infrastructure stub
- [x] NDMA loads/stores
- [x] Asynchronous DMA
